# Generated by Django 5.1.2 on 2025-03-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValuePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
