# Generated by Django 5.1.2 on 2025-05-04 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='search',
        ),
        migrations.AddField(
            model_name='settings',
            name='populated_weekly_spending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WeeklySpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('week_end', models.DateField(unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_spending', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_amount'],
            },
        ),
    ]
