# Generated by Django 5.1.2 on 2025-05-05 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_settings_search_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyspending',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_spendings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklyspending',
            name='week_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weeklyspending',
            name='week_start',
            field=models.DateField(),
        ),
    ]
