# Generated by Django 5.1.2 on 2025-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_monthlyspending'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='populated_monthly_spending',
            field=models.BooleanField(default=False),
        ),
    ]
