# Generated by Django 5.1.2 on 2025-09-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyspending',
            name='custom_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
