# Generated by Django 5.1.2 on 2025-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='error_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
