# Generated by Django 5.1.2 on 2025-05-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_errorlog_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='get_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='post_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
